### ISSUE TITLE
doesn't exist: 'package:invoiceninja_flutter/.env.dart'

### ISSUE THREAD

**Issue by jiangzhixiao** [invoiceninja/flutter-mobile#17]
in auth_middleware.dart 
import 'package:invoiceninja_flutter/.env.dart';
![image](https://user-images.githubusercontent.com/7273487/42441415-b8abbd1c-839a-11e8-9b99-85cd969992f8.png)

**Comment by hillelcoren** [comment]
Thanks for trying out the app!

Try running: `cp lib/.env.dart.example lib/.env.dart`

https://github.com/invoiceninja/flutter-mobile#developer-notes

**Comment by jiangzhixiao** [comment]
@hillelcoren  thanks hilelcoren,btw,i know you just now,i've used your flex-autocomplate for many years:)....
  i'm a beginner of flutter , i know that there is not the place to discuss AIR.but i found Flutter is very similar to AIR,what do you think  hillelcoren

**Comment by hillelcoren** [comment]
Awesome, that was a long time ago...

Totally agreed, Flutter to me feels like a modern version of Flex, I actually wrote about it [here](https://hillelcoren.com/2018/05/18/flutter-is-darts-killer-app/).

**Comment by jiangzhixiao** [comment]
@hillelcoren  in android/app/build.gradle 
 def keystorePropertiesFile = rootProject.file("key.properties")
where is key.properties? when i run debug ,i got the "Can not find the specified file key.properties "

**Comment by hillelcoren** [comment]
Create a file named <app dir>/android/key.properties that contains a reference to your keystore:

storePassword=<password from previous step>
keyPassword=<password from previous step>
keyAlias=key
storeFile=<location of the key store file, e.g. /Users/<user name>/key.jks>

From: https://flutter.io/android-release/

I'll add this to the readme...

**Comment by jiangzhixiao** [comment]
thanks hillelcoren , i just want run debug ,may be it's not necessary to use key.properties??

**Comment by hillelcoren** [comment]
You should be able to undo the changes listed here: https://flutter.io/android-release/

**Comment by jiangzhixiao** [comment]
ok,is there  any test account for login in ? if i should register an account in invoiceninja???

**Comment by hillelcoren** [comment]
Currently you'd need to setup a self host instance of the app, we'll support our hosted version in the future.

**Comment by ankush1432** [comment]
> cp lib/.env.dart.example lib/.env.dart

how to run above command in window

**Comment by ankush1432** [comment]
i am new in flutter 
DriverError: Could not determine URL to connect to application.
Either the VM_SERVICE_URL environment variable should be set, or an explicit
URL should be provided to the FlutterDriver.connect() method.

**Comment by hillelcoren** [comment]
Are you trying to run the Invoice Ninja app?

**Comment by ankush1432** [comment]
yes

**Comment by ankush1432** [comment]
after delete test_driver folder app run 
but next i am not able to login
i am follow both step in developer note
please help me

**Comment by hillelcoren** [comment]
Are you seeing a specific error?
