### ISSUE TITLE
"The getter 'isNotEmpty' was called in null"

### ISSUE THREAD

**Issue by manwithpowers** [invoiceninja/flutter-mobile#18]
Hi,

First, thanks for the great web app and for this new mobile app.
I installed the tester/developer version from Google Play, and am receiving the following error in the app:
`The getter 'isNotEmpty' was called in null`.

I am running a self-hosted installation and the latest version of the web app (4.5.0).

Screenshot attached
![screenshot_20180709-132330](https://user-images.githubusercontent.com/5508635/42448119-7148e3aa-837c-11e8-958d-8f0f8eed282d.png)

**Comment by hillelcoren** [comment]
Thanks for trying out the app!

Another user reported the same error. I'm not seeing it which make me think it's related to specific data not being set. I hope to have a fix in the next release.

**Comment by manwithpowers** [comment]
Great, thanks! Happy to help if you need specifics on my install, etc.

**Comment by robwent** [comment]
I'm seeing this as well, but only on some pages.

On the clients page it shows after a couple of clients.
On the invoices page, it shows in the whole of the content area.

The dashboard displays fine.
Products page seems to be fine (I only have 3 products in the system).

**Comment by robwent** [comment]
On the invoices screen I can get a partial fix by changing the sort order.

Rather than filling the whole screen, the errors only at a certain point.

If I compare to the listings in the webapp then it seems to break on a client that has an umlaut in the name `Gästehaus`.

It looks to be similar for the other screens that can be sorted.

**Comment by hillelcoren** [comment]
This should be fixed in the next version of the mobile app.

**Comment by Sreejith93** [comment]
![Screenshot_2020-04-18-18-31-06-465_com example tamildubbed](https://user-images.githubusercontent.com/56011221/79640427-3106a380-81af-11ea-9330-1479217bf970.png)
  

i have same issue when i open my app.some times work properly some time i got this error

**Comment by hillelcoren** [comment]
- Which versions of the web and mobile app are you using? 
- Which screen do you see the error on?

**Comment by Sreejith93** [comment]
> * Which versions of the web and mobile app are you using?
> * Which screen do you see the error on?

Firestore.instance.collection("postman").getDocuments().then((querySnapshot) {
    querySnapshot.documents.forEach((result) {
      if(querySnapshot.documents == null) return CircularProgressIndicator();
      print(result.data);
      var link = result['link_data'];
       var share = result['share_app'];
       var youtube = result['youtube_link'];
        assert(share is String);
        assert(link is String);
        assert(youtube is String);
        MovieListDemoState.text = share;
        MovieListDemoState.youtubelink = youtube;
        Services.postmanurl = link;
        return Services.postmanurl = link;
    });
  });

this is my code

**Comment by hillelcoren** [comment]
@Sreejith93 If the error you're seeing isn't from the Invoice Ninja app then posting here for help is inappropriate
