### ISSUE TITLE
Login errors when currencies table contains values

### ISSUE THREAD

**Issue by robwent** [invoiceninja/flutter-mobile#19]
Related to an issue reported in slack: https://invoiceninja.slack.com/archives/CBL9F6WJZ/p1531164141000085

Invoiceninja 4.5
After trying to log in through the app I got this error:

![login](https://user-images.githubusercontent.com/411678/42475695-4e22e7a8-83c3-11e8-9d9a-d7652b56b8a0.jpg)

In my database, all exchange_rate values were set to 1.0000 (other than one which was null).

I installed a fresh copy locally and checked the table and all values were null by default. So I set everything to null on my live version and then I could log in.

I'm not sure what modifies the exchange_rate value, since they were all set to the same value 1.000, but it might explain why others weren't running into the same issue.
I have previously sent invoices in 4 different currencies.
I have fixer.io set up for exchange rates.

    EXCHANGE_RATES_ENABLED=true
    XCHANGE_RATES_URL=http://data.fixer.io/latest?access_key=mykey
    EXCHANGE_RATES_BASE=GBP

I can't find anything in the site admin that modifies these values so I'm guessing it's something like the above?

**Comment by hillelcoren** [comment]
Thanks for the details!

**Comment by hillelcoren** [comment]
I've tracked down the problem, the API as sending the exchange rate as a string causing the parsing to fail. Here's the fix, it will be included with the v4.5.1 release. 

https://github.com/invoiceninja/invoiceninja/commit/47783fcd682abf6a1bd79a7e67df2e11b34c28d6
