### ISSUE TITLE
Dashboard stats not correct and multi-currency

### ISSUE THREAD

**Issue by robwent** [invoiceninja/flutter-mobile#20]
When I check the dashboard screen, the time period for each section seems to be different with no way to change it. Some stats are also only for the default currency.

![screenshot_20180709-222507](https://user-images.githubusercontent.com/411678/42476857-23c4fec0-83c7-11e8-97a6-7a015034be3d.jpg)

The invoices sent number is correct and shows the total number of invoices I have sent since installing in any currency.
I have 12 clients in the system, but 2 of them were set up for testing so I assume this is correct as invoices to the test accounts were deleted.
The outstanding value isn't correct. In the web admin I have 2,250.72 total outstanding GBP and 1,896.70 in the last 30 days (all other currencies are fully paid).
I'm not sure where the total revenue is coming from as it doesn't match any of the default timescales for the web dashboard.

I'm not sure where to check average invoice amount in the web app but it also seems very low.

All the stats are for the default currency of the main app, but I also bill in other currencies and there's no way to view those in the mobile app.

**Comment by hillelcoren** [comment]
I think this is two separate issues.

We currently only support showing your primary currency on the dashboard but the totals should match the web dashboard.

**Comment by robwent** [comment]
Seems fine with the latest version
