### ISSUE TITLE
Changing quantity removes unit cost

### ISSUE THREAD

**Issue by Seriousness** [invoiceninja/flutter-mobile#21]
When changing the quantity at the android app it removes the unit cost leaving the invoice with 0,00... maybe a "reset unit cost" or some kinda protection could also help to prevent accidental inputs...

**Comment by hillelcoren** [comment]
Thanks for reporting it! 

It sounds like a bug, I'll try to replicate.

**Comment by hillelcoren** [comment]
I haven't been able to replicate this.

Any chance you can send a screen recording?

**Comment by hillelcoren** [comment]
Quick update.. I'm now able to reproduce the issue.
