### ISSUE TITLE
Login error 4.5.1

### ISSUE THREAD

**Issue by moldovanlaurean** [invoiceninja/flutter-mobile#22]
Invoiceninja 4.5.1

After trying to log in through the app I got this error:

![img_20180731_175436](https://user-images.githubusercontent.com/20583371/43467756-1ead89e0-94eb-11e8-9280-90f184de18cc.png)

Please help me!

**Comment by hillelcoren** [comment]
I'm not sure...

I think this change on v4.5.1 should have fixed the error:

https://github.com/invoiceninja/invoiceninja/commit/47783fcd682abf6a1bd79a7e67df2e11b34c28d6

**Comment by hillelcoren** [comment]
Hmm.. are you sure you're running v4.5.1, it should have already had the change in place. 

Try running this SQL query:

`update currencies set exchange_rate = null;`

Then clear the web app cache by adding `?clear_cache=true` to the end of the URl.

**Comment by hillelcoren** [comment]
Just wanted to check in, have you had a chance to try with the latest versions?

We've released new versions of the web and mobile apps.
