### ISSUE TITLE
Sort invoices by date incorrect

### ISSUE THREAD

**Issue by blizzardengle** [invoiceninja/flutter-mobile#24]
**OS:** Android

**Host Version:** 4.5.2

When I use the sort option to sort invoices by ascending or descending based on the invoices date it is not sorting correctly. For example when choosing descending order I have March invoices at the top and way at the bottom with August in the middle of the list.

**Comment by hillelcoren** [comment]
Thanks, I'll take a look...

**Comment by hillelcoren** [comment]
Thanks for catching this!

We'll include a fix with our next release on Sunday.
