### ISSUE TITLE
App force close since update

### ISSUE THREAD

**Issue by dabenzel** [invoiceninja/flutter-mobile#25]
Hey, I'm using v0.1.4 
Since the update, the app is force closing. I've also deleted APP-Data.

Mobile: Oneplus 6, Android 8.1.0

**Comment by hillelcoren** [comment]
Thanks for letting us know, we're looking into it..

**Comment by dabenzel** [comment]
Hey, installed 0.1.6 a minute ago. Still crashing ;)

**Comment by hillelcoren** [comment]
Thanks for the update! 

It works on the emulator and for some users but is crashing for others. I'll have a new physical device to test with tomorrow.

**Comment by dabenzel** [comment]
Maybe its because my Device ist Rooted and also has Xposed Framework
enabled.

Hillel Coren <notifications@github.com> schrieb am Di., 21. Aug. 2018,
19:15:

**Comment by hillelcoren** [comment]
That's helpful to know but I believe the issue is also affecting phones which haven't been rooted.

**Comment by hillelcoren** [comment]
This should be fixed in v0.1.9

Sorry for the trouble!

**Comment by dabenzel** [comment]
Working again. Thanks!

**Comment by hillelcoren** [comment]
Awesome, thanks for letting us know!

**Comment by pewh** [comment]
I got error `Invalid arguments(s): No host specified in URI /api/v1/login` when try to login. Any issue in server?
