### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by blizzardengle** [invoiceninja/flutter-mobile#29]
The app was instant crashing on Android and after 2 updates (I think that is how many you pushed out) I can now attempt to log in again. The login fails every time though even with all the correct credentials and I get this massive error object in red text printed to the apps login page.

**Comment by hillelcoren** [comment]
Can you post a screenshot of the error.

Also, are you running the latest version of the web app (v4.5.3)

**Comment by blizzardengle** [comment]
I updated to 4.5.3 and the solved the issue.

**Comment by yeahia2508** [comment]
**Getting this error when trying to google login**

`POST: http://www.ninja.test/api/v1/oauth_login?include=tax_rates,users,custom_payment_terms&include_static=true
I/flutter ( 7196): [INFO] LoggingMiddleware: {Action: Instance of 'OAuthLoginRequest', State: Route: /login, CurrencyId: 0, ts: 2018-11-16 03:32:18.789408}
I/flutter ( 7196): SocketException: Failed host lookup: 'www.ninja.test' (OS Error: No address associated with hostname, errno = 7)
I/flutter ( 7196): [INFO] LoggingMiddleware: {Action: Instance of 'UserLoginFailure', State: Route: /login, CurrencyId: 0, ts: 2018-11-16 03:32:18.938355}`

**Comment by blizzardengle** [comment]
This issue was closed, you should open a new issue one.

Just a hunch, I think your domain name is the problem. Are you using `www.ninja.test` or is that coming from Invoice Ninja? Do you own the domain name `ninja.text`? It appears it cant find the website your giving to attempt the OAuthLoginRequest.

Also OAuthLoginRequest should be over HTTPS not HTTP for security reasons.

**Comment by hillelcoren** [comment]
Is the URL (www.ninja.test) correct?
