### ISSUE TITLE
OTP_REQUIRED connecting android beta

### ISSUE THREAD

**Issue by eelco2k** [invoiceninja/flutter-mobile#31]
cannot login with correct usercredentials when  2FA is enabled for that user.

**Comment by hillelcoren** [comment]
Which version of the web app are you using, the mobile app is expecting v4.5.3.

**Comment by eelco2k** [comment]
just updated to master version... (which is higher than v4.5.3 but it states v4.5.3 in footer)

**Comment by eelco2k** [comment]
Weirdly enough when i use "https://invoiceninjadomain.com/api/v1/ping?api_secret=[mysecret]"
the response is: success

**Comment by hillelcoren** [comment]
Sorry, master won't work (unless you want to compile the mobile app yourself).

**Comment by eelco2k** [comment]
Ok, i will revert to tag v4.5.3

**Comment by hillelcoren** [comment]
I think that's best for now, once the new app is out of beta I think master should be ok We're just currently making a lot of changes...
