### ISSUE TITLE
Seems to be missing multi currency settings...

### ISSUE THREAD

**Issue by ssuess** [invoiceninja/flutter-mobile#34]
Hi, First off, LOVE the look and feel of the new app, congrats! I just started testing and at first glance I notice that although in the web version I can see on my dashboard both Dollar and Euro clients, in the ios beta app I cannot. And I see that a couple of them are showing billed in my invoices, but with a dollar sign in front of them instead of Euro.

**Comment by hillelcoren** [comment]
Thanks! Yeah... the dashboard isn't so good right now. It's a placeholder, we're working on redoing it for the next release.

https://twitter.com/hillelcoren/status/1043104300275257344
