### ISSUE TITLE
Sort by invoices Due Date

### ISSUE THREAD

**Issue by svegliando** [invoiceninja/flutter-mobile#39]
I use IN to manage reservation invoices for a small accommodation.  As such the Due Date of the invoice is more important than the invoice date.  The ability to sort by Due Date would be helpful.  In addition, displaying the Due Date as part of the invoice list would be nice to have. (e.g. in addition to the name, amount due, invoice no and invoice status).

**Comment by hillelcoren** [comment]
This has been implemented, thanks for the suggestion!
