### ISSUE TITLE
Error getting a dependency package

### ISSUE THREAD

**Issue by gaojuanjuan** [invoiceninja/flutter-mobile#40]
Because every version of flutter_driver from sdk depends on intl 0.15.6 and invoiceninja_flutter depends on intl ^0.15.7, flutter_driver from sdk is forbidden.
So, because invoiceninja_flutter depends on flutter_driver any from sdk, version solving failed.
pub get failed (1)

**Comment by hillelcoren** [comment]
Thanks for letting us know!

We'll work on this with our next release...

**Comment by hillelcoren** [comment]
This has been fixed
