### ISSUE TITLE
Unable to login to 4.5.7

### ISSUE THREAD

**Issue by starblazr** [invoiceninja/flutter-mobile#44]
Hello,

I'm having an issue with the app and 4.5.7.  App is updated to the latest version and I just updated (and cleared the cache) of my InvoiceNinja selfhost.

I am able to login to Ninja using the old version of the Android app.

![screenshot_20181215-210348](https://user-images.githubusercontent.com/7802036/50049600-6d535c80-00ae-11e9-80ce-797115ee003a.png)

**Comment by hillelcoren** [comment]
I think there may be a problem with your frequencies table.

https://github.com/invoiceninja/invoiceninja/issues/1952#issuecomment-372615055

**Comment by starblazr** [comment]
That was it. There was a yearly NULL value.  I deleted that and the issue
disappeared.

**Comment by hillelcoren** [comment]
Glad to hear it's working!

Note: you may want to re-add the row and make sure your table matches exactly.

**Comment by hillelcoren** [comment]
Also, if you like the app we greatly appreciate reviews on the app store

**Comment by starblazr** [comment]
I was just able to sign into it 10 seconds ago. Give me some time 😀
