### ISSUE TITLE
App not connecting WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by thomas6886** [invoiceninja/flutter-mobile#46]
I found an error when trying to connect to the self-hosted version of the app, I followed the instructions and set the API key. But when I try to connect to it through the app it says:

HandshakeException: Handshake error in client (OS Error: WRONG_VERSION_NUMBER(tls_record.cc:242))

Running Invoice Ninja v4.5.7 and the latest version from the Play store on Android 9.

**Comment by hillelcoren** [comment]
Check if you need to use http or https
