### ISSUE TITLE
Login error: "type '_Smi' is not a subtype of type 'Iterable<dynamic>' in type cast"

### ISSUE THREAD

**Issue by dougti** [invoiceninja/flutter-mobile#47]
Hi,
 When I try to login to my self-hosted site using the latest android app, it fails & returns an error ending with...

`Deserializing '0' to 'BuiltMap<String,bool>' failed due to: type '_Smi' is not a subtype of type 'Iterable<dynamic>' in type cast`

Invoice Ninja 4.5.1
PHP-FPM 7.2

**Comment by hillelcoren** [comment]
You need to use the latest version of the web app.

**Comment by dougti** [comment]
> You need to use the latest version of the web app.

That did the job, cheers Hillel.
