### ISSUE TITLE
Tasks not loading

### ISSUE THREAD

**Issue by oats197** [invoiceninja/flutter-mobile#50]
Hi, thanks for the excellent work your doing -- love this program!

Tasks never show a list, just spins.

I've cleared my phone cache and app, reinstalled the latest app.  Removed the legacy app.  Android 9 latest.

Data on self-hosted 4.5.7.  All data hooks up fine and all views are fine for other areas (ie invoices, quotes, etc)  Tasks just spins and doesn't show any ongoing tasks of any label/type.  Checked change logs on newer 4.5.x versions.  No mention of required for tasks to work.  Nothing in their directly affects my workflow -- maybe I should update the self-host for this to work though? 

Can create a new task.  That shows up in the database and web view from workstation if I hit the cloud in the top right corner of the app.  Task list remains empty on the phone screen.  If I back out of an ongoing task created on the phone (return to task list screen or jump to invoices/other tabs) - I can't return to the running task as it's not listed either. 

I don't believe it's a wait for sync issue as I've only been using this for about 2 months so there are about 200 tasks at most.  Left it spinning for an hour - nothing listed still.

Thanks again.

**Comment by hillelcoren** [comment]
If you want to send test credentials to contact@invoiceninja.com I can try to login to replicate the problem.

**Comment by hillelcoren** [comment]
Got it, thanks! I'll try to get back to you by tomorrow.

**Comment by hillelcoren** [comment]
If you see this error change line 157 of app/Models/Task.php from:

        return $duration;

To:

        return round($duration);
