### ISSUE TITLE
One one resolution image included in the app

### ISSUE THREAD

**Issue by PritishSawant** [invoiceninja/flutter-mobile#55]
This is more of a question than an issue, I noticed you have included only one resolution image, I wonder how come your app did not get rejected on the AppStore.
Not all iPhones use same resolution images. Or did you use different resolution images and not included in this GitHub repo. Can you please guide me how to include different resolution image and how to include them in pubspec.yaml

**Comment by hillelcoren** [comment]
Are you planning on submitting an app using our code to the app store?

**Comment by PritishSawant** [comment]
@hillelcoren No I am not submitting your code to AppStore. Why would I do something like that. Anyways I found the solution to my problem. Thanks
