### ISSUE TITLE
Task IOS App error

### ISSUE THREAD

**Issue by tecnomur** [invoiceninja/flutter-mobile#57]
I'm using 0.1.40 with latest invoiceninja 4.5.12 (self hosted - white label).

https://imgur.com/x9VL9bL

In some tasks.

**Comment by hillelcoren** [comment]
I think the problem may be caused by a task belonging to a task status which has been deleted.

We'll work to include a fix...

**Comment by tecnomur** [comment]
Solved in 0.1.42.

Thanks.
