### ISSUE TITLE
Please remove dependency of google services for app to be usable

### ISSUE THREAD

**Issue by ranch320** [invoiceninja/flutter-mobile#59]
Before the 20 March update from google play store i was able to use the app despite the error message saying that it needs google play services to work.
However after this update i cannot connect to the self-hosted server anymore plus i get the error message as i connect.

For the people who dont use google play services can you please remove the dependency in order to use the app? And no i dont mind if i dont get notifications. I just want the app to be usable without the error message.

Also, Why isnt any of the latest releases shown in the Releases page here since August 2018 ?

**Comment by hillelcoren** [comment]
Can you post the errors you're seeing?

**Comment by ranch320** [comment]
@hillelcoren see screenshot below
![Screenshot_Invoice_Ninja](https://user-images.githubusercontent.com/47230669/55979702-17c14200-5c93-11e9-829f-016b41550086.png)

**Comment by turbo124** [comment]
@ranch320 that is our legacy android app, have you downloaded our new invoice ninja app?

**Comment by ranch320** [comment]
@turbo124 ok thank you!! Its working now perfect and it looks beautiful! i didnt realize there were 2 different versions on playstore.

Thank you for your hard work!

Just wondering why the source code releases are not released under https://github.com/invoiceninja/flutter-mobile/releases since August 2018?

**Comment by hillelcoren** [comment]
The source code is all in the repo we just have been marking the releases.
