### ISSUE TITLE
Not able to login with Google

### ISSUE THREAD

**Issue by NileshRamani** [invoiceninja/flutter-mobile#61]
Not able to login using Google, it's gives an error 401: invalid credential. refer below screenshot.
![Screenshot_2019-04-30-22-00-39-659_com invoiceninja flutter](https://user-images.githubusercontent.com/5783885/56978055-447ec000-6b94-11e9-819a-28da06c05fc8.png)

**Comment by hillelcoren** [comment]
Are you self hosting the app or using our hosted platform?

**Comment by NileshRamani** [comment]
I just installed your android app from Google Play and try to login using Google account.

**Comment by hillelcoren** [comment]
Have you created an account with the same Google login on invoiceninja.com?

**Comment by NileshRamani** [comment]
Yes, I did. 

I don't know but After re-installing android application, now I am able to login using Google. 

Very nice application. 

Thanks for quick reply.

**Comment by hillelcoren** [comment]
Thanks for the update, glad to hear it's working!

**Comment by lukepighetti** [comment]
Just ran into this problem on the production app on iOS.

**Comment by hillelcoren** [comment]
Hmm... have you already created an account in the web app/does the login work in the web app?

**Comment by lukepighetti** [comment]
Nope, that wasn't clear in the mobile app

**Comment by hillelcoren** [comment]
Yeah... it's by design to avoid paying 30%. Coincidentally we've just implemented in-app purchases (Apple required it to submit future updates), it will be available in the next release.
