### ISSUE TITLE
App stuck on the initial logo screen 

### ISSUE THREAD

**Issue by francishero** [invoiceninja/flutter-mobile#62]
I followed all the steps to setup the app but when i run it its just stuck on the home screen 
![image](https://user-images.githubusercontent.com/16598693/57583412-cae0af00-747c-11e9-8fca-d8f53d827434.png)
the logs dont show anything particularly useful except the the no-method error
![image](https://user-images.githubusercontent.com/16598693/57583431-07aca600-747d-11e9-9f95-0ad2763bba9b.png)

What can i do to debug the error? thanks

**Comment by hillelcoren** [comment]
Sorry, hard to say. Maybe try uninstalling the app?

**Comment by liepaja** [comment]
Remove sentry

**Comment by francishero** [comment]
Thanks, it works now

**Comment by hillelcoren** [comment]
We plan to make this easier in the setup.
