### ISSUE TITLE
App release versions aren't tagged

### ISSUE THREAD

**Issue by skylarmt** [invoiceninja/flutter-mobile#73]
It would be great if app versions were tagged in Git and listed on the [Releases page](https://github.com/invoiceninja/flutter-mobile/releases).  It would be even better if the compiled binaries were also uploaded there.  This will help people who don't use Google Play, and give us a way to easily check the latest version so we know when to update.

**Comment by hillelcoren** [comment]
Agreed, we'll work on it...
